config_name: base_ssdu,k=1
description: "base config, k=1"

n_layers: 15
k_iters: 1
epochs: 3

dataset_name: ssdu_dataset
dataset_params:
  dataset_path: 'data/dataset.hdf5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: base_ssdu

restore_weights: False #False, best, inter, final
restore_path: 

loss_name: CrossEntropyLoss
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True